image: alpine:latest

stages:
  - update
  - build
  - run

cache:
  paths:
    - /root/org-app/react-gafmi

update:
  stage: update
  script:
    - cd /root/org-app/react-gafmi && git pull origin dev
  only:
    - dev
  tags:
    - server

build:
  stage: build
  script:
    - cd /root/org-app/react-gafmi && npm install --save --legacy-peer-deps
    - cd /root/org-app/react-gafmi && npm run build
  only:
    - dev
  tags:
    - server

run:
  stage: run
  script:
    - cd /root/org-app/react-gafmi && docker compose up --build -d
  only:
    - dev
  tags:
    - server